"""added_start_date

Revision ID: fdb589385c3c
Revises: 7c1324e64a9c
Create Date: 2021-09-27 13:19:12.036964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdb589385c3c'
down_revision = '7c1324e64a9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alarms', sa.Column('start_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alarms', 'start_date')
    # ### end Alembic commands ###
